import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

import { Navigation } from "@/components/navigation";

const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <title>React + Me</title>
      <body className={roboto.className}>
        <div className="container mx-auto md:px-20 lg:px-60">
          <header className="flex gap-x-16 pb-16 pt-10 items-baseline">
            <div className="logo flex-none">
              R + <span className="text-2xl">🧘🏻</span>
            </div>
            <Navigation />
          </header>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
